### ISSUE TITLE
Error using version 0.3

### ISSUE THREAD

**Issue by zygm0nt** [jducoeur/bootstrap-datepicker-scalajs#3]
I have the following dependencies (seems like the newest ones):

```
        "org.scala-js" %%% "scalajs-dom" % "0.8.0",
        "com.lihaoyi" %%% "scalatags" % "0.4.6",
        "com.lihaoyi" %%% "scalarx" % "0.2.8",
        "com.lihaoyi" %%% "upickle" % "0.2.8",
        "org.querki" %%% "bootstrap-datepicker-facade" % "0.3"
```

And with those I get an error:

```
java.io.IOException: Failed to deserialize info of /home/a/.ivy2/cache/org.scala-js/scalajs-library_2.11/jars/scalajs-library_2.11-0.6.3.jar#scala/math/Ordering$Byte$.sjsir
    at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile$class.info(VirtualFiles.scala:135)
    at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.info(MemFiles.scala:104)
    at org.scalajs.core.tools.optimizer.Linker$PersistentIRFile.updateFile(Linker.scala:310)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$16.apply(Linker.scala:272)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$16.apply(Linker.scala:269)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalajs.core.tools.optimizer.Linker.org$scalajs$core$tools$optimizer$Linker$$updateFiles(Linker.scala:269)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$1.apply(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$1.apply(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:127)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:127)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:126)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:104)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$optimizeCP$1.apply$mcV$sp(ScalaJSOptimizer.scala:74)
    at org.scalajs.core.tools.io.CacheUtils$.cached(CacheUtils.scala:41)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeCP(ScalaJSOptimizer.scala:72)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$14.apply(ScalaJSPluginInternal.scala:147)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$14.apply(ScalaJSPluginInternal.scala:131)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: This version (0.6.3) of Scala.js IR is not supported. Supported versions are: 0.6.0
    at org.scalajs.core.ir.InfoSerializers$Deserializer.readHeader(InfoSerializers.scala:149)
    at org.scalajs.core.ir.InfoSerializers$Deserializer.deserialize(InfoSerializers.scala:100)
    at org.scalajs.core.ir.InfoSerializers$.deserializeWithVersion(InfoSerializers.scala:35)
    at org.scalajs.core.ir.InfoSerializers$.deserialize(InfoSerializers.scala:31)
    at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile$class.info(VirtualFiles.scala:132)
    at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.info(MemFiles.scala:104)
    at org.scalajs.core.tools.optimizer.Linker$PersistentIRFile.updateFile(Linker.scala:310)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$16.apply(Linker.scala:272)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$16.apply(Linker.scala:269)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalajs.core.tools.optimizer.Linker.org$scalajs$core$tools$optimizer$Linker$$updateFiles(Linker.scala:269)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$1.apply(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$1.apply(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:127)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:127)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:126)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:104)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$optimizeCP$1.apply$mcV$sp(ScalaJSOptimizer.scala:74)
    at org.scalajs.core.tools.io.CacheUtils$.cached(CacheUtils.scala:41)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeCP(ScalaJSOptimizer.scala:72)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$14.apply(ScalaJSPluginInternal.scala:147)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$14.apply(ScalaJSPluginInternal.scala:131)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (client/compile:fastOptJS) java.io.IOException: Failed to deserialize info of /home/a/.ivy2/cache/org.scala-js/scalajs-library_2.11/jars/scalajs-library_2.11-0.6.3.jar#scala/math/Ordering$Byte$.sjsir
```

The error does not occur with version 0.1. Perhaps you know what's causing it and how to fix that?

**Comment by jducoeur** [comment]
Which version of Scala.js are you using?  SJS 0.6.3 is required at this point...

**Comment by zygm0nt** [comment]
Upgrading scalajs plugin did actually resolve the problem.
